server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: APPOINTMENT-SERVICE
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**, /doctor/**, /prescriptions/**, /payment/**, /users/**/appointments

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth/**

        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctors/**

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost