spring.datasource.url=jdbc:mysql://database:3306/bmc
spring.data.mongodb.host=mongodb_container
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
app.kafka.bootstrap-servers=kafka:9092
