
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-107-23-47-123.compute-1.amazonaws.com:8761/eureka/

    instance:
      ec2-107-23-47-123.compute-1.amazonaws.com

  instance:
    hostname: ec2-107-23-47-123.compute-1.amazonaws.com